check failure 1

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -3,25 +3,15 @@ name: Testing stuff
 on:
   push:
     branches:
-      - master
+      - feature-2
 
 jobs:
   a_test_job:
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v3
-      - name: github context
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: echo "$GITHUB_CONTEXT"
-      - name: commits
-        env:
-          COMMITS: ${{ toJson(github.event.commits) }}
-        run: echo "$COMMITS"
-      - name: commit messages
-        env:
-          COMMIT_MESSAGES: ${{ toJson(join(github.event.commits.*.message, ', ')) }}
-        if: ${{!contains(env.COMMIT_MESSAGES, '#skip')}}
-        run: |
-          echo ${{env.COMMIT_MESSAGES}}
-          echo "$COMMIT_MESSAGES"
+      - name: Failing step
+        id: demo
+        run: exit 1
+      - name: The demo step has failed
+        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
+        run: echo "fail"
