integrating branches

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -30,8 +30,16 @@ jobs:
       - name: deploy
         if: success()
         uses: superfly/flyctl-actions/setup-flyctl@master
-      - run: flyctl deploy --remote-only
-        env:
+
+      - name: http check
+        run: |
+            if curl -sSf http://localhost:5000/dummy/health | grep -q 'ERROR' ; then
+                echo "Health check failed. Deployment aborted."
+                exit 1
+            else 
+                flyctl deploy --remote-only
+            fi
+        env: 
             FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
 
 
