health check .ex.11

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -34,4 +34,19 @@ jobs:
         env:
             FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
 
+<<<<<<< Updated upstream
 
+=======
+      - name: monitor deployment
+        run: |
+            APP_URL = "https://fso-cicd-pokedex.fly.dev"
+
+            if curl -sSf ${APP_URL}/dummy/health | grep -q 'internal error'; then
+                echo "Health Check failed.deployment aborted"
+                exit 1
+            else 
+                echo "Deployment successful."
+            fi
+        env:
+            FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
+>>>>>>> Stashed changes
